# Code generated by:
# python -m pwiz -e mysql -u bot-admin -i teambot -P teambot
# Date: September 14, 2016 12:21AM
# Database: teambot
# Peewee version: 2.8.3

from peewee import *
from util import *

database = MySQLDatabase(db_name, **{'user': db_user, 'password': db_pwd})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class Task(BaseModel):
    content = CharField(null=True)
    create_time = DateTimeField(null=True)
    due_time = DateTimeField(null=True)
    from_user = CharField(null=True)
    from_user_id = CharField(null=True)
    id = BigIntegerField(primary_key=True)
    owner_first_name = CharField(null=True)
    owner = BigIntegerField(db_column='owner_id', null=True)
    priority = IntegerField(null=True)
    status = IntegerField(null=True)

    class Meta:
        db_table = 'Task'

class Team(BaseModel):
    admin = CharField(null=True)
    email = CharField(null=True)
    id = BigIntegerField(primary_key=True)
    name = CharField(null=True)
    owner = CharField(null=True)
    register_time = DateTimeField(null=True)
    token = CharField(null=True)
    uri = CharField(null=True)

    class Meta:
        db_table = 'Team'

class User(BaseModel):
    first_name = CharField(null=True)
    id = BigIntegerField(primary_key=True)
    last_name = CharField(null=True)
    register_time = DateTimeField(null=True)
    slack_userid = CharField(null=True)
    slack_username = CharField(null=True)
    status = IntegerField(null=True)
    team = BigIntegerField(db_column='team_id', null=True)
    team_uri = CharField(null=True)

    class Meta:
        db_table = 'User'

