# Code generated by:
# python -m pwiz -e mysql -u bot-admin -i teambot -P teambot
# Date: September 12, 2016 12:27AM
# Database: teambot
# Peewee version: 2.8.3

from peewee import *

database = MySQLDatabase('teambot', **{'user': 'bot-admin', 'password': 'bot@teambot'})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class Team(BaseModel):
    admin = CharField(null=True)
    email = CharField(null=True)
    id = BigIntegerField(primary_key=True)
    name = CharField(null=True)
    owner = CharField(null=True)
    register_time = DateTimeField(null=True)
    token = CharField(null=True)
    uri = CharField(null=True)

    class Meta:
        db_table = 'Team'

class Todo(BaseModel):
    content = CharField(null=True)
    create_time = DateTimeField(null=True)
    due_time = DateTimeField(null=True)
    from_user = CharField(null=True)
    id = BigIntegerField(primary_key=True)
    priority = IntegerField(null=True)
    status = IntegerField(null=True)
    user = BigIntegerField(db_column='user_id', null=True)

    class Meta:
        db_table = 'Todo'

class User(BaseModel):
    first_name = CharField(null=True)
    id = BigIntegerField(primary_key=True)
    last_name = CharField(null=True)
    register_time = DateTimeField(null=True)
    slack = CharField(db_column='slack_id', null=True)
    slack_username = CharField(null=True)
    status = IntegerField(null=True)
    team_uri = CharField(null=True)
    token = CharField(null=True)

    class Meta:
        db_table = 'User'

